# Generated by Django 2.2.5 on 2020-11-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0002_annotation_preprocesseddataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='image_url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
