# Generated by Django 2.2.5 on 2020-11-03 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0003_annotation_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='preprocessed_dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_api.PreprocessedDataset'),
        ),
    ]
