# Generated by Django 2.2.5 on 2020-11-07 14:59

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0004_auto_20201103_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preprocesseddataset',
            name='ready',
        ),
        migrations.AddField(
            model_name='preprocesseddataset',
            name='class_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None),
        ),
        migrations.AddField(
            model_name='preprocesseddataset',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='preprocesseddataset',
            name='preprocessing_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
