# Generated by Django 2.2.5 on 2020-11-07 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0005_auto_20201107_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='preprocesseddataset',
            name='detector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_api.Detector'),
        ),
        migrations.AlterField(
            model_name='preprocesseddataset',
            name='dataset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_api.Dataset'),
        ),
    ]
