# Generated by Django 2.2.5 on 2020-11-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0006_auto_20201107_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preprocesseddataset',
            old_name='preprocessing_time',
            new_name='time',
        ),
        migrations.AddField(
            model_name='preprocesseddataset',
            name='status',
            field=models.TextField(choices=[('PE', 'pending'), ('FA', 'failed'), ('SU', 'succeded')], default='PE', max_length=2),
        ),
    ]
