# Generated by Django 2.2.5 on 2020-11-10 15:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0007_auto_20201107_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation',
            old_name='image_url',
            new_name='rgb_url',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='boxes',
        ),
        migrations.AddField(
            model_name='annotation',
            name='rgb_boxes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='thermal_boxes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='thermal_url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
