# Generated by Django 2.2.5 on 2020-11-10 15:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0008_auto_20201110_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preprocesseddataset',
            name='class_list',
        ),
        migrations.AddField(
            model_name='detector',
            name='class_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None),
        ),
    ]
