# Generated by Django 2.2.5 on 2020-11-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0009_auto_20201110_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='path',
            new_name='rgb_path',
        ),
        migrations.AddField(
            model_name='dataset',
            name='thermal_path',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
