# Generated by Django 2.2.5 on 2020-11-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0010_auto_20201111_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='detector',
            name='is_both',
            field=models.BooleanField(default=False),
        ),
    ]
