# Generated by Django 2.2.5 on 2020-11-18 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0013_annotation_checker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='rgb_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='thermal_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='rgb_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
